### ISSUE TITLE
Argocd access from ingress

### ISSUE THREAD

**Issue by basava1139** [devopshobbies/argocd-tutorial#1]
Hi ,
I am facing issues while connecting argocd ui from ingress,
I tried lots of time but I am not able to understand where the issues.  I am able to do ingress from other services but not able to do in argocd

**Comment by mohammadll** [comment]
Hi @basava1139  Please provide your Ingress configuration here. As you probably know, we installed ArgoCD using different methods, such as Ingress, in the second episode. You can follow that as well.

**Comment by basava1139** [comment]
I used this below values and and even updated dns  in etc hosts file but still I am not getting 
 server:
   ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingressClassName: nginx
    hosts:
    - devops.hobbies
    paths:
      - /
    pathType: Prefix
    https: true

**Comment by mohammadll** [comment]
@basava1139  I've now checked the original Helm chart of ArgoCD and found that some keys have been changed and updated in the `server.ingress` block. To solve your issue, use the configuration below:

    server:
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        ingressClassName: nginx
        hostname: "devops.hobbies"

And also add `--enable-ssl-passthrough` as an additional argument to the `Ingress-nginx deployment`

**Comment by mohammadll** [comment]
Hi @basava1139 Did you solve this issue? If you did, I want to close it

**Comment by basava1139** [comment]
yes , issue was solved, thanks for helping
